git:
  pagers:
    - pager: ""
    - pager: delta --dark --paging=never
    - externalDiffCommand: difft --color=always
    - pager: ydiff -p cat -s --wrap --width={{columnWidth}}
      colorArg: never
